@startuml ViewSequence
title GUI - View Update/Draw Sequence

participant ":ViewControl" as ViewControl

collections "Views" as Views
participant ":View" as View

participant ":Container" as Container

collections "Components" as Components
note right: Children
participant ":Component" as Component

collections "Controls" as Controls
note right: Children
participant ":Control" as Control

ViewControl -> Views : Update()
Views -> View : Update()
View -> Container: Update()
Container -> Components: Update()
Components -> Component: Update()
Components <-- Component: Update()
Container <-- Components: Update()
Container -> Controls: Update()
Controls -> Control: Update()
Control -> Control: HandleInput()
Controls <-- Control: Update()
Container <-- Controls: Update()
View <-- Container: Update()
View -> View: HandleInput()
Views <-- View : Update()
ViewControl <-- Views : Update()

@enduml