@startuml ViewSequence
title GUI - View Update/Draw Sequence

participant ":ViewControl" as ViewControl

collections "Views" as Views
participant ":View" as View

participant ":Container" as Container

collections "Children" as Components
participant ":Component" as Component

collections "Controls" as Controls
participant ":Control" as Control

ViewControl -> Views : Update()
    Views -> View : ForEach()
        View -> View : HandleInput()
        View -> Container : Update()
            Container -> Controls : Update()
                Controls -> Control : ForEach()
                    Control -> Control : HandleInput()
                Controls <- Control : ForEach()
            Container <-- Controls : Update()
            Container -> Components : Update()
                Components -> Component : ForEach()
                    Component -> Component : Update()
                Components <-- Component : ForEach()
            Container <-- Components : Update()
        View <-- Container : Update()
    Views <-- View : ForEach()
ViewControl <-- Views : Update()

@enduml