@startuml ViewSequence
''''''''
'Page 1'
''''''''
title GUI - View Update Sequence

participant ":ViewControl" as ViewControl

collections "Views" as Views
participant ":View" as View

participant ":Container" as Container

collections "Children" as Components
participant ":Component" as Component

collections "Controls" as Controls
participant ":Control" as Control

ViewControl -> Views : Update()
activate Views

    Views -> View : ForEach()
    activate View

        View -> View : HandleInput()
        activate View
        deactivate View

        View -> Container : Update()
        activate Container

            Container -> Controls : Update()
            activate Controls

                Controls -> Control : ForEach()
                activate Control

                    Control -> Control : HandleInput()
                    activate Control
                    deactivate Control

                Controls <-- Control
                deactivate Control

            Container <-- Controls
            deactivate Controls

            Container -> Components : Update()
            activate Components

                Components -> Component : ForEach()
                activate Component

                    Component -> Component : Update()
                    activate Component
                    deactivate Component

                Components <-- Component
                deactivate Component

            Container <-- Components
            deactivate Components

        View <-- Container
        deactivate Container

    Views <-- View
    deactivate View

ViewControl <-- Views
deactivate Views

''''''''
'Page 2'
''''''''
newpage GUI - View Draw Sequence

ViewControl -> Views : Draw()
activate Views

    Views -> View : ForEach()
    activate View

        View -> Container : Draw()
        activate Container

            Container -> Components : Draw()
            activate Components

                Components -> Component : ForEach()
                activate Component

                    Component -> Component : Draw()
                    activate Component
                    deactivate Component

                Components <-- Component
                deactivate Component

            Container <-- Components
            deactivate Components

        View <-- Container
        deactivate Container

    Views <-- View
    deactivate View

ViewControl <-- Views
deactivate Views

@enduml